player removeEventHandler ["HandleDamage",player getVariable ["eams_revive_ehHandleDamage",-1]];
//player removeEventHandler ["Dammaged",player getVariable ["eams_revive_ehDammaged",-1]];
//player removeEventHandler ["HandleHeal",player getVariable ["eams_revive_ehHandleHeal",-1]];
player removeEventHandler ["Killed",player getVariable ["eams_revive_ehKilled",-1]];
player removeEventHandler ["Respawn",player getVariable ["eams_revive_ehRespawn",-1]];
